name: leketoys
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.2386172
  lightness: 0.9215774
  brandColors:
    - '#BAB4A6'
    - '#0B0D0A'
    - '#7D694E'
    - '#F2EEE5'
    - '#C2512F'
  rhythmicContrast: 0.8113934
typography_spectrum: 0.6096122
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0.1922428
