name: leketoys
favicon: null
layout_spectrum: 0.1922428
typography_spectrum: 0.6096122
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Portfolio of Håvard Legreid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BAB4A6'
    - '#0B0D0A'
    - '#7D694E'
    - '#F2EEE5'
    - '#C2512F'
  brandStrength: 0.2386172
  lightness: 0.9215774
  saturation: 1
  rhythmicContrast: 0.8113934
purpose: []
